path: ./
train: images/train
val: images/val

train_labels: labels/train
val_labels: labels/train

names: 
    0: ignored regions
    1: pedetrian
    2: people
    3: bicycle
    4: car
    5: van
    6: truck
    7: tricycle
    8: awning-tricycle
    9: bus
    10: motor
    11: others

